# fly.toml app configuration file generated for fitness-server-datn on 2023-06-10T15:34:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fitness-server-datn"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
